---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - dynatrace.eda.dt_esa_api:
        dt_api_host: "{{ dynatrace_url }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: 60 (Default is 1 min) i.e plugin runs every 1 minute

  rules:
    - name: Problem payload Dynatrace for CPU issue
      condition: event.payload.problemTitle contains "CPU saturation"
      action:
        run_job_template:
          name: "Remediate CPU saturation issue"
          organization: "Default"